CREATE TABLE `extended_profile` (
	`uname` VARCHAR(100) NOT NULL,
	`contact` VARCHAR(256) NULL DEFAULT NULL,
	`notes` VARCHAR(4000) NULL DEFAULT NULL,
	`flag1` INT(10) UNSIGNED NULL DEFAULT NULL,
	`flag2` INT(10) UNSIGNED NULL DEFAULT NULL,
	`flag3` INT(10) UNSIGNED NULL DEFAULT NULL,
	`has_avatar` TINYINT(1) NULL DEFAULT NULL,
	`settings` VARCHAR(10000) NULL DEFAULT NULL,
	PRIMARY KEY (`uname`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
